# Generated by Django 4.2.3 on 2023-11-20 22:34

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_myuser_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyUser",
        ),
        migrations.CreateModel(
            name="Person",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
