# Generated by Django 4.2.3 on 2024-05-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product_id",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.item",
            ),
        ),
    ]
