# Generated by Django 4.2.3 on 2024-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_remove_cartitem_product_id_cartitem_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
